config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'jobs#index'
  resources :jobs do
    collection do
      get :fulltime
      get :parttime
      get :freelance
      get :remote
    end
  end

end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :job_class, presence: true
  validates :job_type, presence: true
  validates :company, presence: true
  validates :description, presence: true
  validates :link, presence: true

  belongs_to :owner, class_name: "User", foreign_key: :user_id

  def editable_by?(user)
    user == owner
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end

  def new
    @job = Job.new
  end

  def create
    @job = current_user.jobs.new(job_params)

    if @job.save
      redirect_to jobs_path, notice: "新增工作成功"
    else
      render :new
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  def edit
    @job = current_user.job.find(params[:id])
  end

  def update
    @job = current_user.job.find(params[:id])

    if @job.update(job_params)
      redirect_to jobs_path, notice: "修改工作成功"
    else
      render :edit
    end
  end

  def destroy
    @job = current_user.job.find(params[:id])
    @job.destroy
    redirect_to jobs_path, alert: "刪除工作成功"
  end

  def fulltime
    @jobs = Job.where(job_class: "full-time")
  end

  def parttime
    @jobs = Job.where(job_class: "part-time")
  end

  def freelance
    @jobs = Job.where(job_class: "freelance")
  end

  def remote
    @jobs = Job.where(job_class: "remote")
  end

  private

  def job_params
    params.require(:job).permit(:job_class, :job_type, :company, :description, :link)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_message
    alert_types = {notice: :success, alert: :danger}
    close_button_options = {class: "close", "data-dismiss" => "alert", "aria-hidden" => true}
    close_button = content_tag(:button, "x", close_button_options)

    alerts = flash.map do |type, message|
      alert_content = close_button + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"

      content_tag(:div, alert_content, class: alert_class)
    end

    alerts.join("\n").html_safe
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/common/_footer.html.haml
%footer.container{:style => "margin-top: 100px;"}
  %p.text-center Build by Rorusage

app/views/common/_navbar.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  .container-fluid
    .navbar-header
      %button.navbar-toggle{:type => "button", "data-toggle" => "collapse", "data-target" => "#example-navbar-collapse"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} Jobs Board

    .collapse.navbar-collapse{:id => "example-navbar-collapse"}
      %ul.nav.navbar-nav
        %li= link_to("All Jobs", jobs_path)
        %li= link_to("Full-time", fulltime_jobs_path)
        %li= link_to("Part-time", parttime_jobs_path)
        %li= link_to("Freelance", freelance_jobs_path)
        %li= link_to("Remote", remote_jobs_path)

      %ul.nav.navbar-nav.navbar-right
        - if !current_user
          %li= link_to("Sign up", new_user_registration_path)
          %li= link_to("Log in", new_user_session_path)
        - else
          %li.dropdown
            %a.dropdown-toggle{:href => "#", "data-toggle" => "dropdown"}
              Hi, #{current_user.name}
              %b.caret
            %ul.dropdown-menu
              %li= link_to("New Jobs", new_job_path)
              %li= link_to("Edit account", edit_user_registration_path)
              %li= link_to("Log out", destroy_user_session_path, method: :delete)

app/views/jobs/_form.html.haml
.col-md-12.text-center
  - jobs.each do |j|
    %h1= link_to(j.job_type, job_path(j))
    %h4= j.company
    %hr

app/views/jobs/edit.html.haml
.col-md-4.col-md-offset-4
  %h1 編輯工作
  %hr

  = simple_form_for @job do |f|
    .form-group
      = f.input :job_class, collection: ["full-time", "part-time", "freelance", "remote"]
      = f.input :job_type, input_html: {class: "form-control"}
      = f.input :company, input_html: {class: "form-control"}
      = f.input :description, input_html: {class: "form-control"}
      = f.input :link, input_html: {class: "form-control"}
    = f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submitting..."}

app/views/jobs/freelance.html.haml
= render "form", jobs: @jobs

app/views/jobs/fulltime.html.haml
= render "form", jobs: @jobs

app/views/jobs/index.html.haml
%h1 Hello

app/views/jobs/new.html.haml
.col-md-4.col-md-offset-4
  %h1 新增工作
  %hr

  = simple_form_for @job do |f|
    .form-group
      = f.input :job_class, collection: ["full-time", "part-time", "freelance", "remote"]
      = f.input :job_type, input_html: {class: "form-control"}
      = f.input :company, input_html: {class: "form-control"}
      = f.input :description, input_html: {class: "form-control"}
      = f.input :link, input_html: {class: "form-control"}
    = f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submitting..."}

app/views/jobs/parttime.html.haml
= render "form", jobs: @jobs

app/views/jobs/remote.html.haml
= render "form", jobs: @jobs

app/views/jobs/show.html.haml
.col-md-4.col-md-offset-4
  %h3{:style => "text-decoration:underline"} #{@job.job_type}
  %h4 Job class       : #{@job.job_class}
  %h4 Company         : #{@job.company}
  %h4 Job Description : #{@job.description}
  %a{:href => "#{@job.link}"} More Info
  %hr
  = link_to("Back", jobs_path, class: "btn btn-primary btn-left")
  - if @job.editable_by?(current_user)
    = link_to("Edit", edit_job_path(@job), class: "btn btn-info")
    = link_to("Delete", job_path(@job), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure"})

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobsBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
  <%= render "common/navbar"%>
  <%= notice_message %>
  <%= yield %>
</div>

<%= render "common/footer"%>

</body>
</html>